apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv
  namespace: opentelemetry
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/opt/volume"

