apiVersion: v1
kind: Service
metadata:
 name: otel
 namespace: opentelemetry
 labels:
   app: opentelemetry
   component: otel-collector
spec:
 type: ClusterIP
 ports:
   - name:  {{ default "otlp-grpc"  .Values.service_ports.name1 }} # Default endpoint for OpenTelemetry gRPC receiver.
     port:  {{ default 4317  .Values.service_ports.port1 }}
     protocol: TCP
     targetPort: {{ default 4317  .Values.service_ports.targetport1 }}
   - name: {{ default "otlp-http"  .Values.service_ports.name2 }} # Default endpoint for OpenTelemetry HTTP receiver.
     port: {{ default 4318  .Values.service_ports.port2 }}
     protocol: TCP
     targetPort: {{ default 4318  .Values.service_ports.targetport2 }}
  #  - name: zpages
  #    port: 55679
  #    protocol: TCP
  #    targetPort: 55679
  #  - name: health-check
  #    port: 13133
  #    protocol: TCP
  #    targetPort: 13133
 selector:
   app: opentelemetry
   name: optl
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-headless
  namespace: opentelemetry
  labels:
   app: opentelemetry
   component: optl-collector
spec:
  ports:
  - port: 16686
    name: web
  - port: 14250
    name: optl-connection
  - port: 4317
    name: grpc
  clusterIP: None
  selector:
       app: opentelemetry
       component: optl-collector
       name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: opentelemetry
  labels:
   app: opentelemetry
   component: optl-collector
   name: jaeger
spec:
  ports:
    - name: {{ .Values.jaeger_query_ports.name }}
      port: {{ .Values.jaeger_query_ports.port }}
      protocol: TCP
  selector:
      app: opentelemetry
      component: optl-collector
      name: jaeger
  type: {{ .Values.jaeger_query_ports.type }}
